apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool-deployment
  labels:
    app: nginx-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx
        ports:
        - containerPort: 8080
        env:
        - name: NGINX_HTTP_PORT_NUMBER
          value: "8080"
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8081
        env:
        - name: HTTP_PORT
          value: "8081"
