apiVersion: v1
kind: Pod
metadata:
  name: multitool-test-pod
  labels:
    app: multitool-test
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    ports:
    - containerPort: 80
